version: 2.1
orbs:
  aws-ecr: circleci/aws-ecr@6.0.0
  aws-ecs: circleci/aws-ecs@0.0.8
workflows:
  build-and-deploy:
    jobs:
      - aws-ecr/build-and-push-image:
          repo: ${ECR_REPOSITORY_NAME}
          tag: latest
          dockerfile: ./transmission/Dockerfile
          path: ./transmission/
      - aws-ecs/deploy-service-update:
          requires:
            - aws-ecr/build-and-push-image
          family: ${ECS_SERVICE_NAME}
          cluster-name: ${ECS_CLUSTER_NAME}
          container-image-name-updates: 'container=${ECS_SERVICE_NAME},tag=latest'
